In [1]:
import torch

# 3x4 크기의 랜덤 값을 가진 텐서 생성
tensor = torch.rand(3, 4)

# 생성된 텐서의 두 번째 열을 모두 0으로 변경
tensor[:, 1] = 0

# 텐서의 모든 원소를 합한 값 계산
tensor_sum = torch.sum(tensor)

tensor, tensor_sum.item()


(tensor([[0.7169, 0.0000, 0.3628, 0.9614],
         [0.5407, 0.0000, 0.3420, 0.9329],
         [0.3734, 0.0000, 0.1991, 0.7542]]),
 5.183506011962891)

In [3]:
import torch

# 5x5 크기의 랜덤 텐서 생성 (0~1 사이의 균일 분포)
tensor = torch.rand(5, 5)
print("생성된 텐서:\n", tensor)

# 값이 0.5보다 큰 값만 추출하여 1차원 텐서로 변환
mask = tensor > 0.5
result = tensor[mask].flatten()
print("0.5보다 큰 값들:\n", result)

생성된 텐서:
 tensor([[0.7278, 0.0382, 0.0804, 0.0520, 0.3410],
        [0.2084, 0.3740, 0.2292, 0.3091, 0.6425],
        [0.2721, 0.5637, 0.2318, 0.7228, 0.1586],
        [0.4741, 0.0535, 0.5001, 0.1673, 0.0192],
        [0.6591, 0.6504, 0.5484, 0.0436, 0.4015]])
0.5보다 큰 값들:
 tensor([0.7278, 0.6425, 0.5637, 0.7228, 0.5001, 0.6591, 0.6504, 0.5484])


In [4]:
import numpy as np
import torch

# 4x4 크기의 랜덤 NumPy 배열 생성
numpy_array = np.random.rand(4, 4)
print("NumPy 배열:\n", numpy_array)

# NumPy 배열을 PyTorch Tensor로 변환
tensor = torch.from_numpy(numpy_array)
print("Tensor:\n", tensor)

# Tensor를 파일로 저장 (torch.save)
torch.save(tensor, 'my_tensor.pt')
print("Tensor가 파일로 저장되었습니다.")

# 저장된 파일에서 Tensor 불러오기
loaded_tensor = torch.load('my_tensor.pt')
print("불러온 Tensor:\n", loaded_tensor)

# 원본 Tensor와 불러온 Tensor 비교 (torch.equal)
if torch.equal(tensor, loaded_tensor):
    print("두 Tensor는 동일합니다.")
else:
    print("두 Tensor가 다릅니다.")

NumPy 배열:
 [[0.43149849 0.59325513 0.32168599 0.91427846]
 [0.12820305 0.15502603 0.60113535 0.11622248]
 [0.19813143 0.72552258 0.1347216  0.77121571]
 [0.76437703 0.75575872 0.44910634 0.99194489]]
Tensor:
 tensor([[0.4315, 0.5933, 0.3217, 0.9143],
        [0.1282, 0.1550, 0.6011, 0.1162],
        [0.1981, 0.7255, 0.1347, 0.7712],
        [0.7644, 0.7558, 0.4491, 0.9919]], dtype=torch.float64)
Tensor가 파일로 저장되었습니다.
불러온 Tensor:
 tensor([[0.4315, 0.5933, 0.3217, 0.9143],
        [0.1282, 0.1550, 0.6011, 0.1162],
        [0.1981, 0.7255, 0.1347, 0.7712],
        [0.7644, 0.7558, 0.4491, 0.9919]], dtype=torch.float64)
두 Tensor는 동일합니다.


<ipython-input-4-08a605b38951>:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_tensor = torch.load('my_tensor.pt')
